[package]
name = "libindigo"
version = "0.1.0+INDIGO.2.0.289"
edition = "2021"

[dependencies]
url = "2.5.2"
libindigo-sys = { path = "sys" }
enum_primitive = "0.1.1"
lazy_static = "1.5.0"
once_cell = "1.19.0"
log = "0.4.22"

[dev-dependencies]
test-log = "0.2.16"