[workspace]

members = [
    ".",
    "app", "relm",
    "sys",
]

[package]
name = "libindigo"
version = "0.1.0+INDIGO.2.0.289"
edition = "2021"

[dependencies]
log = "0.4.22"
url = "2.5.2"
hostname-validator = "1.1.1"
libindigo-sys = { path = "sys" }
enum_primitive = "0.1.1"
lazy_static = "1.5.0"
once_cell = "1.19.0"
strum = "0.26.3"
strum_macros = "0.26"
parking_lot = "0.12.3"
function_name = "0.3.0"
fragile = "2.0.0"

[dev-dependencies]
test-log = "0.2.16"
